### ISSUE TITLE
'on scroll' script firing at the wrong place

### ISSUE THREAD

**Issue by gorhgorh** [probberechts/cactus-dark#13]
hi there I'm testing Cactus and found that the on scroll listener [here](https://github.com/probberechts/cactus-dark/blob/master/source/js/main.js#L48) assume a "post" layout (having a nested [#menu > #nav](https://github.com/probberechts/cactus-dark/blob/master/source/js/main.js#L49)). that is not the case for the home nor for pages.

behaviour is testable on your own demo, open the dev tool, reduce browser height and trigger a scroll to see the errors in console.

I made a fork with a [simple fix](https://github.com/gorhgorh/cactus-dark/commit/fe96edd0c5f74c6319c0fe84700e4d832f51c204), but i think making this post menu available in pages would be even better, isn't it?

**Comment by probberechts** [comment]
Thanks for letting me know this.

I don't think your quick fix is entirely correct. I could be wrong, however, but I think the else part is unreachable. That part of the code definitely needs to be refactored some time, but for now the commit I just made at least removes the error.

I don't like the idea of making the post menu available in pages. I prefer to use a uniform layout for the home, archive and about page.

**Comment by gorhgorh** [comment]
thanks for the fix, and about the menu, we probably don't use the theme for the same reasons hence my demand, since i'm using pages as well and you seems not too. i'll see if i don't change pages to post, since the little auto generated TOC is rad for the post format i'm using

anyway thanks for this nice and simple to hack on theme :)
