### ISSUE TITLE
how to configure writing to paging?

### ISSUE THREAD

**Issue by YGLau** [probberechts/cactus-dark#16]
in my `_config.yml`

![screen shot 2017-01-25 at 14 21 15](https://cloud.githubusercontent.com/assets/17176518/22280154/fbf18756-e309-11e6-98e1-ef825b8b908d.png)

but the writing page can not show other articles except first page, so how can do it?
thx~

**Comment by probberechts** [comment]
Pagination is not (yet) implemented on the archives page. You should disable it (show all posts in one long list), or implement it yourself.
