### ISSUE TITLE
Not all post show up in archive?

### ISSUE THREAD

**Issue by spl0i7** [probberechts/cactus-dark#17]
So, I was trying out cactus-dark but there seem to be a strange problem that not all post show up in archive page, although if I use the url from generate log I can access the pages. How can I fix this?

**Comment by probberechts** [comment]
Do only the X most recent posts show up? If so, see #16.

Otherwise, I need more information to address the problem. Have these posts specific [front-matter](https://hexo.io/docs/front-matter.html)? Is there a public repo for your blog or is it published somewhere?

**Comment by spl0i7** [comment]
thanks, now I see that pagination is not yet implemented so only 10 posts showed up. so disabling it seems to fix that.

**Comment by walkerwzy** [comment]
hi, how to disable pagination?

**Comment by probberechts** [comment]
@walkerwzy 
```
per_page: 0
```
