### ISSUE TITLE
style.css not getting recreated when generating after highlight colorschemes change

### ISSUE THREAD

**Issue by stsourlidakis** [probberechts/cactus-dark#18]
Hello, not sure if this belongs here or to hexo's repository.
`style.css` is not getting recreated when running `hexo generate` after changing the highlight colorscheme, you have to delete the file from `/public/css` and then ```hexo generate```.

**Comment by probberechts** [comment]
I just tested it and it works fine for me (using Hexo 3.2.2).
Did you try running `hexo clean`? Usually that command fixes these kind of problems. If the problem persists, I advise you to create an issue in Hexo's repository.

**Comment by stsourlidakis** [comment]
It works if I run `hexo clean` **every** time before `hexo generate`, probably because it deletes /public.
Thanks for the help, I'll create a new issue in Hexo's repository.
