### ISSUE TITLE
How does a Archives or Writing page are generated ?

### ISSUE THREAD

**Issue by tunacon** [probberechts/cactus-dark#19]
I try to modify a title of Writing page so i don't know what file i should modify.

ex. Change a title from tunacon to Writing
http://tunacon.com/archives/

Anyone can explain me how does a archives page working?

**Comment by probberechts** [comment]
The relevant code is in [layout/_partial/head.ejs](https://github.com/probberechts/cactus-dark/blob/master/layout/_partial/head.ejs#L39)
```html
<title><%= page.title ? page.title : config.title %></title>
``` 

For the Page template the `page.title` variable is used, while for the other templates the `config.title` variable is used by default. If you would like to set a custom title for the archives page you will have to change this logic. Take a look at [this blogpost](http://1pixelout.net/2015/09/18/writing-hexo-template-helpers/) which describes how to do this.

**Comment by tunacon** [comment]
Thank you @probberechts . It's working now ^ ^
