### ISSUE TITLE
Markdown code block font size is very large on the phone. 

### ISSUE THREAD

**Issue by Fantasy9527** [probberechts/cactus-dark#22]
Markdown code block font size defaults to 13px.

But on my phone ,the font becomes 20px.

Your demo has the same problem on the phone.

[your demo](https://probberechts.github.io/cactus-dark/2016/11/01/An-overview-of-all-Markdown-elements/#Code-Blocks)

Do not see the problem on the Developer tools;

**Comment by Fantasy9527** [comment]
if code length very much,and container's width more than sreen's width.
code's font size is 20px on the iphone.

I am sorry.
my english is no good.
I hope you know what I mean.

**Comment by probberechts** [comment]
I don't have this problem on the iPhone6, nor on my Android phone. Could you post a screenshot?

**Comment by Fantasy9527** [comment]
## iPhone SE.
![iPhone SE](http://note.youdao.com/yws/public/resource/ba7a471ae0bcb301095e5ee63aebbc95/xmlnote/FC87C5138DB44BAEAE9B7A8C70FDDD0B/1620)



## iPhone 7 plus
![iPhone 7 plus](http://note.youdao.com/yws/public/resource/ba7a471ae0bcb301095e5ee63aebbc95/xmlnote/088C5046198C420C8154A37AC0B416A2/1625)

**Comment by Fantasy9527** [comment]
I didn't have the problem on my iPad.

I inspect  this element with chrome.
The font size is normal.
So is safari.

**Comment by probberechts** [comment]
There is something wrong with your screenshots, I can only see the top part. Can you fix this?

**Comment by Fantasy9527** [comment]
ok. I have already fix the bug

**Comment by probberechts** [comment]
`-webkit-text-size-adjust: none` disables text resizing entirely. When you hit ⌘+, the images and layout will get bigger, but text will stubbornly remain the same size. This is almost never what you want. Therefore, I changed it to `-webkit-text-size-adjust: 100%`. Could you verify if it is fixed?

Thanks for helping me fix this!

**Comment by Fantasy9527** [comment]
input cmd to the code
```
hexo clean 
hexo g
```   
ParseError


   30|   ‑webkit‑text‑size‑adjust: 100%
   31|   antialias()
   32|
   33| .content
-------^
   34|   flex: 1
   35|   @extend $base-style
   36|

expected "indent", got "outdent"

if remove  ‑webkit‑text‑size‑adjust: 100%, parse is OK
