### ISSUE TITLE
Can I show more than 5 articles on my homepage?

### ISSUE THREAD

**Issue by ihewro** [probberechts/cactus-dark#25]
thank for your effort first.

I'm not well in English,please forgive.

my blog have more than  5 articles,but the homepage can only show latest five posts.

can show more articles?

or can set Pagination to show more articles?

thanks a lot.

**Comment by probberechts** [comment]
There is a variable for this: `theme.customize.post_count`.
For example, if you would like to show the 10 most recent posts on the home page, add this snipped to the theme's config file (`cactus-dark/_config.yml`):

```yml
customize:
    post_count: 5
```

**Comment by ihewro** [comment]
I get it.

Adding a Paging button will be better.

Thank you for your reply.
