### ISSUE TITLE
How to config "about" page?

### ISSUE THREAD

**Issue by pollyfat** [probberechts/cactus-dark#28]
My about page jump to 404 now. :(

And thanks for create such a lovely theme. 💯

**Comment by probberechts** [comment]
You can create the about page with
```
hexo new page about
```
Next, create some content in `source/about/index.md`. See [the documentation](https://hexo.io/docs/writing.html) for more info.

If you would like to change the layout of the about page, you will have to edit `theme/cactus-dark/layout/page.ejs`.
