### ISSUE TITLE
<% if (config.description) { %>

### ISSUE THREAD

**Issue by Code-Tap** [probberechts/cactus-dark#3]
In the index.ejs file this statement is on line 2

I would like to know what file i need to add where to get the _description_ text to render in this location on the index page like in your demo.

I presume its done in a similar way to how the projects bit is done.

Thanks

**Comment by probberechts** [comment]
```config.description``` is a variable [provided by Hexo](https://hexo.io/docs/configuration.html). You should set it in the root ```_config.yml``` file.

For example, this is the the relevant part from the ```_config.yml```file of the demo:

  ```
   ...
   title: Cactus Dark
   description: Hi, I'm a theme for the [Hexo](http://hexo.io) blogging framework. I'm particularly great for a personal web page with a simple blog. In this paragraph, you can provide some information about yourself. Below, you're most recent or highlited writings and projects are listed.  
   author: Pieter Robberechts 
   ...
   ```

**Comment by Code-Tap** [comment]
Excellent thank you ( im _very_ new to hexo )
