### ISSUE TITLE
TOC disappear if there's heading level 1 in the page content

### ISSUE THREAD

**Issue by kong0107** [probberechts/cactus-dark#31]
In `source\css\_partial\post\actions_desktop.styl`, there's a rule setting `#header-post #toc .toc-level-1` to `display: none`.
This means that not only are first-level-headings invisible in TOC, but also their descendants in the nested list are gone.

If first-level-headings are hidden in purpose, maybe just hide `.toc-level-1 > .toc-link` could be considered.

This issue also applies to `#footer-post #toc-footer .toc-level-1`, which is set to `display: none` in `actions_mobile.styl`.

**Comment by probberechts** [comment]
The only first level heading in your post should by your blog post title, which is indeed hidden on purpose. However, I am aware that some people will ignore this best practice. So, thanks for signalling this. I will make the change.

(BTW: I am sorry for the late response)
