### ISSUE TITLE
New page doesn't create index.html

### ISSUE THREAD

**Issue by adnphllps** [probberechts/cactus-dark#34]
Using the command example:
`hexo new page 'notes'`

Creates a directory under source 'notes' containing index.md. After editing the markdown and generating the 'notes' directory is created under public, but instead of the expected index.html the index.md file is on the generated site.

**Comment by probberechts** [comment]
I just tried it and if I run (using Hexo v3.2.2)
```
hexo new page 'notes'
hexo generate
```
The file ```public/notes/index.html``` is generated correctly.

Your issue is definitely not related to this theme, so I suggest you create an issue in the general Hexo repo.
