### ISSUE TITLE
Pagination for long posts

### ISSUE THREAD

**Issue by AerialAdv** [probberechts/cactus-dark#38]
Hi. Great theme!

I have some very long posts which I would like to be paginated in a similar way to the way you recently added pagination to the archives page.

I have tried using the "******" and "‐‐‐‐‐‐" markdown syntax which is sometimes used for page breaks, but this only produces a horizontal rule.

Please can you advise whether this is possible with the theme - if not, would you consider adding it.

Thanks

**Comment by probberechts** [comment]
It is not a theme related feature, but should be implemented in Hexo itself or by a plugin. So far, Hexo does not support it and, as far as I know, there are no plugins that provide this functionality. However, I noticed that paginating of a blog post is part of the [Hexo 4.0 Roadmap](https://github.com/hexojs/hexo/issues/2492), so you will have to be patient (and maybe put some pressure or the developers). Of course, it would be even better to implement it yourself/provide some help 😉
