### ISSUE TITLE
Unexpected spaces in nav before text

### ISSUE THREAD

**Issue by HowieHz** [probberechts/cactus-dark#388]
https://probberechts.github.io/hexo-theme-cactus/cactus-white/public/2016/11/14/hello-world/
![image](https://github.com/probberechts/hexo-theme-cactus/assets/94725606/5d83de1c-9ef6-4773-b1bc-c13892c8d88c)
![image](https://github.com/probberechts/hexo-theme-cactus/assets/94725606/95de17c5-5244-4f9b-a6bc-aed8d69e3617)

https://probberechts.github.io/hexo-theme-cactus/cactus-white/public/
![image](https://github.com/probberechts/hexo-theme-cactus/assets/94725606/c9b95670-ad6a-4759-9c77-866b7e1bce40)
![image](https://github.com/probberechts/hexo-theme-cactus/assets/94725606/63b77cd5-fde1-4d96-8c2e-ac442025ed07)

**Comment by foxB612** [comment]
I think this is already fixed by a15f8ace0f9a144ea8356c7c38d11f2f85652ea5?

**Comment by HowieHz** [comment]
> I think this is already fixed by [a15f8ac](https://github.com/probberechts/hexo-theme-cactus/commit/a15f8ace0f9a144ea8356c7c38d11f2f85652ea5)?

I'm not sure, if so close this issue, thanks!

**Comment by HowieHz** [comment]
I'm not very good at ejs, but this issue has probably been fixed already
