### ISSUE TITLE
share menu has some problems

### ISSUE THREAD

**Issue by gaunthan** [probberechts/cactus-dark#39]
Hi. 
I found cactus-dark doesn't work very well on Firefox 53.0.3:

- On mobile view, the share menu doesn't shown after click.  
- On desktop view, some share item lost its icon.

Thanks for all and waiting your reply :-D.

**Comment by probberechts** [comment]
Does it print any errors in the console and could you try with all your plugins disabled?

At least it works on Mac OS Sierra with Firefox 54.0. I don't have v53.0.3 installed, but I will take a closer look at it within a week or two when I have more time.

**Comment by gaunthan** [comment]
My apology...After disabled all plugins,  the problem is **solved**. I should realize that  **AdbBlock Plus** will remove the social media link...

Thanks a lot! :+1:

**Comment by probberechts** [comment]
No problem.
