### ISSUE TITLE
Is it possible to have the number of page visits on the theme ? 

### ISSUE THREAD

**Issue by SofianeHamlaoui** [probberechts/cactus-dark#390]
Hello,

I was wondering if it’s possible to get the number of visits/views/reads on a a blogpost on the cactus theme ? 

Thank you in advance

**Comment by probberechts** [comment]
https://github.com/probberechts/hexo-theme-cactus?tab=readme-ov-file#analytics

**Comment by SofianeHamlaoui** [comment]
> https://github.com/probberechts/hexo-theme-cactus?tab=readme-ov-file#analytics

It’s already setup, but I want to get the unique visits for each page of my blog.
