### ISSUE TITLE
Upload Demo Site Files for Various Needs Please

### ISSUE THREAD

**Issue by washere** [probberechts/cactus-dark#395]
HI,

I love this elegant theme, so thank you.

I could not find the posts of the demo site in the zip file for code, as download or git clone version.
I also searched online.

It would be great if the developer or anyone who has them could zip into a file and upload the demo site markdown files & assets as:

1) a sub-folder in repository here
2) elsewhere on GitHub as a fork or new project 
3) or as a zip file anywhere online (mediafire etc)

And post the download link in this issue thread to help future users after closing it.

Because the sections in the demo website will be great for people to quickly create protocol sections for video, gallery etc etc.

It will help spread the use and fame of this wonderful theme by showing how much more than a theme it is.

Thanks again.

**Comment by probberechts** [comment]
See https://github.com/hexojs/hexo-theme-unit-test/tree/master

**Comment by washere** [comment]
THANK YOU, you are an angel :)

future searchers, it is all here as he said:

https://github.com/hexojs/hexo-theme-unit-test/tree/master/source/_posts

Might be good idea to post above link in the theme's homepage readme so mere mortals like me see it.

Thanks again for EVERYTHING.
