### ISSUE TITLE
Page Layout slightly off-centre

### ISSUE THREAD

**Issue by Code-Tap** [probberechts/cactus-dark#4]
Hi,
I have setup the about page, and i have discovered that the layout has shifted slightly to the right on these pages. But it is perfect on the main page.
Im unsure how this has happened or what i can do to correct it.

the only change i made was to rename it from Writings to archives
![screenshot from 2016-11-17 16-31-30](https://cloud.githubusercontent.com/assets/23399537/20397931/5a40fb00-ace3-11e6-8114-50876641788c.png)

thank you

**Comment by probberechts** [comment]
Thanks for reporting this! This commit should fix it.

**Comment by Code-Tap** [comment]
Awesome, you fixed that CSS issue perfectly.
## thanks!
