### ISSUE TITLE
How to remove the "#" symbol in front of each tag?

### ISSUE THREAD

**Issue by lxw0109** [probberechts/cactus-dark#40]
As shown on the [demo page](https://probberechts.github.io/cactus-dark/2016/11/14/hello-world/), there is a "#" symbol in front of each tag, how can I remove them?
Thank you

**Comment by hlldz** [comment]
Remove the "content" parameter;

```
article .content h2:before {
    content: "#";
    color: #2bbc8a;
    position: absolute;
    left: -1rem;
    top: -4px;
    font-size: 1.2rem;
    font-weight: bold;
}

```

**Comment by lxw0109** [comment]
hi, @hlldz 
Thank you for your help. I tried as what you suggested, but it seemed not working. Thanks for your suggestion, I tried to remove the `content` parameter in `.article-tag .tag-link:before`, it works.
```css
.article-tag .tag-link:before {
  //content: "#";
}
```
