### ISSUE TITLE
how to always display the menu in the article page on the top-right?

### ISSUE THREAD

**Issue by BlackBeatles** [probberechts/cactus-dark#41]
the theme so best

**Comment by probberechts** [comment]
In [actions_desktop.styl](https://github.com/probberechts/cactus-dark/blob/master/source/css/_partial/post/actions_desktop.styl#L47-L48) change
```css
  #menu
    visibility: hidden
```
to
```css
  #menu
    visibility: visible
```
to display the menu by default.

**Comment by BlackBeatles** [comment]
@thanks

**Comment by BlackBeatles** [comment]
@probberechts thanks

**Comment by BlackBeatles** [comment]
@probberechts can you help me delete this issue? thanks
