### ISSUE TITLE
Document how you add label and link to code blocks

### ISSUE THREAD

**Issue by R4meau** [probberechts/cactus-dark#42]
Please, document how you managed to add those to the code block on the "Hello World" post.

![please-document](https://user-images.githubusercontent.com/3984265/28495688-46389c1c-6f25-11e7-9dfb-f7942a3255e9.png)

I couldn't find it online for some reason. Also, let me know if we can do tabbed code blocks too:

![tabbed](https://user-images.githubusercontent.com/3984265/28495702-b3f16888-6f25-11e7-9422-53aa457175dd.png)

I got this screenshot from the Tranquilpeak theme by Louis Barranqueiro: http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2015/03/23/highlighted-code-showcase/

**Comment by R4meau** [comment]
Oh and, what about line numbers?

**Comment by R4meau** [comment]
Okay, figured it out:
\`\`\`py Hello world https://github.com/r4meau  hello_world.py

print "Hello World!"
\`\`\`

But still nothing for the line numbers even though `line_number` under `highlight` is set to true. Also, nothing for tabbed code blocks.

**Comment by R4meau** [comment]
Okay, figured out how to do the tabbed code blocks: https://stackoverflow.com/questions/35140300/how-to-implement-a-tabbed-codeblock-tag-for-hexo

Hopefully I'll figure out why the line numbers aren't showing up.

**Comment by probberechts** [comment]
I disabled line numbers in the css. You can enable it by removing [this line](https://github.com/probberechts/cactus-dark/blob/master/source/css/style.styl#L165)

I was not aware there existed such a `line_number` config option. I will change the code over the weekend to incorporate this option.

**Comment by R4meau** [comment]
Great! Thanks. Also, I realized that the code blocks don't support empty lines for some reason. Mind fixing that in the next update too? Sorry for not just contributing, I already got so much on my hand at the moment. You're probably pretty busy too. :)
