### ISSUE TITLE
Disable greyed out logo?

### ISSUE THREAD

**Issue by chelmzy** [probberechts/cactus-dark#45]
Hello. Thanks for the wonderful theme! I was just wondering if there is an option to allow the logo to always be coloured instead of greyed out until you hover over it.

Thanks!

**Comment by hlldz** [comment]
Hi,

Remove `filter: grayscale(100%);` in style.css file.

**Comment by probberechts** [comment]
Don't edit the compiled css file. It might get overwritten if you execute `hexo generate`. Instead remove
```stylus
    -webkit-filter: grayscale(100%)
    filter: grayscale(100%)
```
from [the original stylus file](https://github.com/probberechts/cactus-dark/blob/0cdc9c3af1166f5a0a9756619c84e3428376c2ef/source/css/_partial/header.styl#L31-L32).

There is no config option to change this. (Providing a predefined config option for all such possible small design tweaks is practically infeasible and would result in bloated code).
