### ISSUE TITLE
how to put a blockquote in the top-right/left corner of a paragraph？

### ISSUE THREAD

**Issue by chong-w** [probberechts/cactus-dark#48]
As shown below：
![2](https://user-images.githubusercontent.com/30772228/30127520-2b8b5b90-9372-11e7-803a-7c29b0d74709.JPG)

and if possible， how to put a picture in the same position？

**Comment by probberechts** [comment]
To put a blockquote in the top-right/left corner of a paragraph:
```
{% pullquote right %}
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque hendrerit lacus ut purus iaculis feugiat. 
{% endpullquote %}
```
This is called a pullquote. See https://hexo.io/docs/tag-plugins.html#Pull-Quote

You can use the same principle for images. See https://hexo.io/docs/tag-plugins.html#Image

**Comment by chong-w** [comment]
THX a lot！
