### ISSUE TITLE
about local search

### ISSUE THREAD

**Issue by effie999** [probberechts/cactus-dark#52]
I found that local search can not be used...

like this.
![fireshot capture 023 - search - https___foretime fueis com_search_](https://user-images.githubusercontent.com/13113431/31836553-b62f1230-b610-11e7-97ac-33407dfef691.png)

**Comment by probberechts** [comment]
It works for me.

Maybe try to verify these things:
- Are there any errors in the Javascript console?
- Is the `search.xml` file generated?
- Does it work on <https://probberechts.github.io/cactus-dark/search/>?
- Try to disable all your browser plugins
