### ISSUE TITLE
Social media links often blocked by adblocker

### ISSUE THREAD

**Issue by gjbianco** [probberechts/cactus-dark#55]
Using even the non-aggressive settings in uBlock Origin, a lot of the social media links get `display: none;`.

The two main triggers I'm seeing are having the ID of "sociallinks" and the title attributes on the links (at least for Twitter).

I was able to resolve this locally by removing the title attribute and changing the ID to something like "socialinfo". I can open a PR for this later.

**Comment by probberechts** [comment]
Thanks for figuring this out. Neither the ID nor title attributes are essential, so you can change/remove them. I will wait for you pull request.
