### ISSUE TITLE
how to show project lists after Creating a projects file source/_data/projects.json

### ISSUE THREAD

**Issue by huainanzi** [probberechts/cactus-dark#58]

**Comment by probberechts** [comment]
It should show up automatically once you create that file. Note that you should create this file in your root `source/` folder, not in `themes/cactus-dark/source/`.

If it still does not work, try to run `hexo clean` once and regenerate.

**Comment by probberechts** [comment]
Is this problem solved by now?

**Comment by huqianshan** [comment]
I have the save question before i see the issue, but i have set the `default show_all_posts: true` in the `_config.yml.`
thanks for sharing..
