### ISSUE TITLE
More language, plz ~

### ISSUE THREAD

**Issue by FantaZZ** [probberechts/cactus-dark#65]
More language, plz ~

**Comment by probberechts** [comment]
Unfortunately, my knowledge of Chinese is non-existent. However, I am willing to accept a pull request for a Chinese translation if someone can provide it.

Some time ago, @lidecong created one (#61), but he closed it before I could check it. 

@lidecong: Why did you close the pull request? Could you reopen it?

**Comment by FantaZZ** [comment]
You could add i18n path like defalt theme `/themes/landscape/languages` .

Like this
```
-rw-r--r-- 1 root root 319 Jan 18 19:29 default.yml
-rw-r--r-- 1 root root 330 Jan 18 19:29 de.yml
-rw-r--r-- 1 root root 344 Jan 18 19:29 es.yml
-rw-r--r-- 1 root root 374 Jan 18 19:29 fr.yml
-rw-r--r-- 1 root root 398 Jan 18 19:29 ja.yml
-rw-r--r-- 1 root root 363 Jan 18 19:29 ko.yml
-rw-r--r-- 1 root root 348 Jan 18 19:29 nl.yml
-rw-r--r-- 1 root root 319 Jan 18 19:29 no.yml
-rw-r--r-- 1 root root 372 Jan 18 19:29 pt.yml
-rw-r--r-- 1 root root 506 Jan 18 19:29 ru.yml
-rw-r--r-- 1 root root 323 Jan 18 19:29 zh-CN.yml
-rw-r--r-- 1 root root 323 Jan 18 19:29 zh-TW.yml
```

We can DIY.

**Comment by lidecong** [comment]
My apologies. I'm open a new pull request.
Hey, @FantaZZ the font-family for Chinese I set 'sans-serif', and I'm feel better, you can try others.
@probberechts I just think, maybe just you wanna a simple theme no more language at the start, so I close it. My apologies again.

**Comment by lidecong** [comment]
And another point make me confused. When I using hexo default theme 'landscape', i didn't set the language, so it random display the language, isn't English. even it have 'default.yml' is English. I don't know it will be happen or not. Anyway, It seem you have to tell some body to setting if the theme have more language.

**Comment by FantaZZ** [comment]
@probberechts   Do not worry about translation file. 
If you could make code support i18n. 
That is great ~
If there has a `/themes/landscape/languages/default.yml`, everyone can translate to they want.

@lidecong already pull request for a Chinese translation.  But maybe not include all words you want.

**Comment by probberechts** [comment]
So, I have added i18n support in the last commit (0d8fcf07e5aec80c65e9ce45ca80819d2bed2013). 
Although, I had to remove @lidecong's Chinese translation, since it was missing some translations. Feel free to send a new push request.

Also, let me know if I missed something or if some part is not compatible with Chinese.
