### ISSUE TITLE
About Image Title

### ISSUE THREAD

**Issue by Crossady** [probberechts/cactus-dark#68]
It seems that image title can not be shown in the page
I used both way
```
![](test.jpg "test title") 
{% asset_img "test.jpg" "test title" %}
```
and all it can just show the image itself, and nothing about the title.
Is there a way to show title?

Anyway, thank you for the theme. I like it very much.

**Comment by Crossady** [comment]
well maybe i can add a title by myself just below the image

**Comment by probberechts** [comment]
FYI, `![](test.jpg "test title")` corresponds to `<img src="test.jpg" title="test title">`. This `title` attribute is not the same as a caption, but is shown as a tooltip in most browsers. See <https://www.w3schools.com/tags/att_global_title.asp> for more info.
