### ISSUE TITLE
How to add reading time plugin? 

### ISSUE THREAD

**Issue by apolytos** [probberechts/cactus-dark#7]

**Comment by probberechts** [comment]
You should take a look at the plugin's [README](https://github.com/ierhyna/hexo-reading-time/blob/master/README.md)

**In short:**
1. In your site's main directory execute:
  ```
  npm install --save hexo-reading-time
  ```

2. Add the following line to `layout/post.ejs`:
  ```ejs
  <%- readingTime(page.content) %>
  ```

**Comment by apolytos** [comment]
I got it to work, sorry for creating an issue for nothing, I was kinda frustrated trying to get it to work in another theme, apollo. Sadly that theme has jade files instead of ejs.
