### ISSUE TITLE
Sorry, I don't know how to configure "Tags", can u help me?

### ISSUE THREAD

**Issue by ifelseboyxx** [probberechts/cactus-dark#73]
my `.md` file configure my tag just like this:
![](https://user-images.githubusercontent.com/24642787/36137599-f3ad958a-10d0-11e8-9133-582f8a48ae5c.jpeg)

and it show too! but if I click this tag,it just jump to "404"...
<img width="389" alt="1111" src="https://user-images.githubusercontent.com/24642787/36137668-32a89f1e-10d1-11e8-9584-e52489004bfe.png">

**Comment by probberechts** [comment]
I am not sure, but I think that `tags: [ObjC]` is invalid YAML syntax. Could you try to use either
```yaml
tags:
    - ObjC
```
or
```yaml
tags: ["ObjC"]
```

If that does not work, where does the link point to?

**Comment by ifelseboyxx** [comment]
It's still does not work . The link like :
<img width="821" alt="3333" src="https://user-images.githubusercontent.com/24642787/36141944-92ad3284-10e1-11e8-8343-0fce264b9a8c.png">
and I find if I use http://localhost:4000/  all tags work!

**Comment by probberechts** [comment]
Right, but if you look at the HTML, what is the content of the `href` attribute?

**Comment by ifelseboyxx** [comment]
I find the reason. It's so stupid write "Objc" as "ObjC". I'm so sorry wasting your time. @probberechts

**Comment by probberechts** [comment]
No problem. I'm happy you could solve it.
